import org.junit.Test;

import static org.junit.Assert.assertFalse;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pfcui' at '2/23/16 6:24 PM' with Gradle 2.8
 *
 * @author pfcui, @date 2/23/16 6:24 PM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertFalse("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
