/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pfcui' at '11/24/15 1:30 PM' with Gradle 2.4
 *
 * @author pfcui, @date 11/24/15 1:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
