version: '3'
services:
  app:
    build: .
    ports:
      - "7071:7071"    
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true # docker run -i
    tty: true        # docker run -t      