# This is a comment
FROM ubuntu:14.04
MAINTAINER Cui Pengfei
RUN apt-get install tree
CMD echo "hello, test github integration with docker, how much data gets generated if i change this text? what happens now? install tree"
