/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pfcui' at '2/23/16 6:24 PM' with Gradle 2.8
 *
 * @author pfcui, @date 2/23/16 6:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
